version: "3.5"
services:
  mongo_db:
    container_name: mongo-db
    image: mongo
    ports:
      - "27017:27017"
    restart: unless-stopped
    networks:
      - mongo_network

  mongo_app:
    container_name: mongo-app
    build: .
    ports:
      - 8082:8082
    environment:
      spring.data.mongodb.host: mongo_db
      spring.data.mongodb.port: 27017
      spring.data.mongodb.authentication-database: admin
      server.port: 8082
    restart: unless-stopped
    depends_on:
      - mongo_db
    networks:
      - mongo_network

networks:
  mongo_network:
    name: mongo_network
    driver: bridge
